# development:
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   database: demo_app
#   username: root
#   password: root
#   host: 127.0.0.1
#   port: 3306

development:
 adapter: postgresql
 encoding: unicode
 database: co_demo_app
 pool: 5
 username: postgres
 password: postgres